version: 2.0.4.{build}-{branch}

branches:
  only:
    -master

install:
  - cmd: update.bat

nuget:
  disable_publish_on_pr: true

build_script:
  - cmd: fake CreatePackage

test:
  assemblies: 
    - Test\bin\Debug\Test.dll

deploy:
  - provider: GitHub
    tag: '{APPVEYOR_REPO_TAG_NAME}'
    release: v{APPVEYOR_REPO_TAG_NAME}
    auth_token:
      secure: Dx8eB38O4hJW/LQJFYyIvLnIkUtEY0RtcKZqjh4fS2Ij2fnAoI87zK+Iif+uiIAx
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true
  
  - provider: NuGet
    api_key:
      secure: 5+5/ePYUVDkfxaM2M41t3tFCau5y8spzxa4Wf0J20RPxLEURWgF7cq3qOEqNz1ik
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true

