version: 5.0.1.{build}-{branch}
image: Visual Studio 2019
branches:
  only:
    - master
build_script:
  - ps: .\build.ps1
nuget:
  disable_publish_on_pr: true
artifacts:
  - path: deploy/*.nupkg
    name: Nuget Package
test: off
deploy:
  - provider: GitHub
    tag: '${APPVEYOR_REPO_TAG_NAME}'
    release: 'Release ${APPVEYOR_REPO_TAG_NAME}'
    description: 'Release ${APPVEYOR_REPO_TAG_NAME}'
    auth_token:
      secure: 9lcqgfNgqSltyjFe2LCuC1ArZ2SGlmf7bZPeyMpXZoLujPaDIkj1z7Gxgrord1Z8
    artifact: /.*\.nupkg/
    on:
      branch: master
      APPVEYOR_REPO_TAG: true

  - provider: NuGet
    api_key:
      secure: ObGf47lAlW65uQ+k06EPWHW3OYbYPEHanUQMu3/lZc5bIGttfkytXT3FDjsgPqT5
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: master
      APPVEYOR_REPO_TAG: true

