version: 5.0.0.{build}-{branch}

branches:
  only:
    - master

install:
  - cmd: update.bat

nuget:
  disable_publish_on_pr: true

artifacts:
  - path: 'deploy\*.nupkg'

build_script:
  - cmd: build.bat Pack

test:
  assemblies:
    - Test\bin\Release\net5.0\Test.dll

deploy:
  - provider: GitHub
    tag: '{APPVEYOR_REPO_TAG_NAME}'
    release: 'Release {APPVEYOR_REPO_TAG_NAME}'
    auth_token:
      secure: Dx8eB38O4hJW/LQJFYyIvLnIkUtEY0RtcKZqjh4fS2Ij2fnAoI87zK+Iif+uiIAx
    artifact: /.*deploy\\.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true

  - provider: NuGet
    api_key:
      secure: 5+5/ePYUVDkfxaM2M41t3tFCau5y8spzxa4Wf0J20RPxLEURWgF7cq3qOEqNz1ik
    artifact: /.*deploy\\.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true

